// generated by gen_cond_take_kern_impls.py
#include "../kern.inl"

namespace megdnn {
namespace cuda {
namespace cond_take {

inst_genidx(::megdnn::dtype::Int32)
#undef inst_genidx

inst_copy(::megdnn::dtype::Int32)
#undef inst_copy
#undef inst_copy_

}  // cond_take
}  // cuda
}  // megdnn
