// generated by gen_batch_cuda_conv_bias_kern_impls.py
#include "../batch_conv_bias_int8_gemm_ncdiv4hw4_ldg_128.cuinl"

template void megdnn::cuda::batch_conv_bias::do_batch_conv_bias_int8_gemm_ncdiv4hw4_ldg_128<PerChannelBiasVisitor, 
        IConvEpilogue<Activation<megdnn::param_enumv::BatchConvBias::NonlineMode::IDENTITY>>>(
        const int8_t* d_src, 
        const int8_t* d_filter,  
        PerChannelBiasVisitor bias, 
        IConvEpilogue<Activation<megdnn::param_enumv::BatchConvBias::NonlineMode::IDENTITY>> epilogue, 
        const ConvParam& param, 
        float alpha, 
        float beta, 
        cudaStream_t stream);
