FROM ubuntu:20.04

ENV UID=1024 PATH=${PATH}:/usr/local/cuda/bin

# update
RUN apt-get update -y

# build env
RUN DEBIAN_FRONTEND=noninteractive \
TZ=Etc/UTC apt-get install -y \
pkg-config build-essential git-lfs \
autoconf gdb git-core gnupg flex bison gperf \
zip curl zlib1g-dev gcc \
g++ rsync wget vim llvm clang

# install cmake 3.15.2
RUN cd /tmp ; wget https://cmake.org/files/v3.15/cmake-3.15.2.tar.gz;tar -xzvf cmake-3.15.2.tar.gz;cd cmake-3.15.2;./configure; make -j8; make install

# install base python3
RUN apt-get install -y python3
RUN apt-get update -y && apt-get install --fix-missing && apt-get install -y python3-dev python3-pip python3-numpy python3-setuptools

# install pyenv
RUN curl https://pyenv.run | bash

# install more env for build python3 from src
RUN apt-get install -y checkinstall libncursesw5-dev \
libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libreadline-dev \
libffi-dev liblzma-dev libncurses5-dev libdb-dev libexpat-dev libtinfo5 libtinfo-dev

# install more env for build swig and ninja
RUN apt-get install -y libpcre3 libpcre3-dev re2c

# call other build env
ADD init_ubuntu2004.sh /tmp
RUN /tmp/init_ubuntu2004.sh && rm -f /tmp/init_ubuntu2004.sh

# install lsb-release to distinguish is ubuntu or manylinux
RUN apt-get install -y lsb-release

# install gcc/g++ 8 as gcc/g++ 9 as issue: some code will take about 1h to run as on aarch64-ubuntu
RUN apt-get install -y gcc-8 g++-8
